### ISSUE TITLE
Option to add recurring tasks

### ISSUE THREAD

**Issue by scientisco** [zurichat/zc_plugin_todo#120]

**Comment by trojan782** [comment]
I will take this
TrojanCodes

**Comment by trojan782** [comment]
I will take this

**Comment by pepps01** [comment]
@Ericogia @EricOgie  Please see link to my PR  https://github.com/zurichat/zc_plugin_todo/pull/464

**Comment by pepps01** [comment]
@Ericogia Please see the latest PR for your Review https://github.com/zurichat/zc_plugin_todo/pull/464

**Comment by pepps01** [comment]
@meshmmanuel  and @mista_cee Please help review my latest PR  https://github.com/zurichat/zc_plugin_todo/pull/464
