### ISSUE TITLE
Add route to get a collection of tasks created by a specific user

### ISSUE THREAD

**Issue by Ajibola03** [zurichat/zc_plugin_todo#161]
Create a route to handle a request for all tasks created by a specific user by id.

**Comment by Alpha2Chris14** [comment]
Add route to get task by specific user

**Comment by promisszn** [comment]
create route

**Comment by promisszn** [comment]
Task : Added route to get task collection for a user by id
Live link: https://todo.zuri.chat/api/task_collection/8

[Link to PR](https://github.com/zurichat/zc_plugin_todo/pull/365)

[Link to code](https://github.com/zurichat/zc_plugin_todo/pull/365/files)
