### ISSUE TITLE
Create a reusable todo item component 

### ISSUE THREAD

**Issue by Ruthiejayjay** [zurichat/zc_plugin_todo#176]
Create a reusable todo item component

**Comment by Kemmie001** [comment]
Please assign this issue to me

**Comment by Kemmie001** [comment]
Create a reusable task card component that contains the task title, description, collaborators date etc.

[View live link ](https://todo.zuri.chat/#/main) 

[View the component code](https://github.com/zurichat/zc_plugin_todo/blob/develop/resources/js/components/taskCard.vue) 

[View router code](https://github.com/zurichat/zc_plugin_todo/blob/develop/resources/js/pages/Main.vue) 

[View pull request link ](https://github.com/zurichat/zc_plugin_todo/pull/286)

**Comment by markessien** [comment]
Nice :+1:
