### ISSUE TITLE
Create function to upload files 

### ISSUE THREAD

**Issue by Ruthiejayjay** [zurichat/zc_plugin_todo#186]

**Comment by Eno-obongEnoh25** [comment]
Assign to me

**Comment by Eno-obongEnoh25** [comment]
Link to live test: https://todo.zuri.chat/api/files
This function enables the upload of a file to a todo task.

**Comment by markessien** [comment]
Broken and no clear way to test

**Comment by Eno-obongEnoh25** [comment]
A file has to be selected. A post request on postman to the live link
uploads the file. No other method of testing an api link without a frontend

**Comment by Eno-obongEnoh25** [comment]
This life link is an endpoint that uploads a file. It returns no values on its own, but when a file is selected (on postman perhaps), the link enables the file to be uploaded

**Comment by Eno-obongEnoh25** [comment]
This life link is an endpoint that uploads a file. It returns no values on its own, but when a file is selected (on postman perhaps), the link enables the file to be uploaded

https://todo.zuri.chat/api/files
