### ISSUE TITLE
Add An Endpoint That Display Static Information About TODO Plugin

### ISSUE THREAD

**Issue by EricOgie** [zurichat/zc_plugin_todo#204]
Create and add an endpoint that Displays static information about  TODO plugin .

[View Live Link](https://todo.zuri.chat/info) 
As you can observe from the Live-Link, The chained endpoint, https://todo.zuri.chat/info,  displays static Information of the TODO Plugin in JSON format when you hit the URL link.

From the JSON displayed on the [Live Link](https://todo.zuri.chat/plugin-info), you would notice the JSON information included the plugin SideBar URL,  HTML_URL,  and a pingable URL to check if the plugin is still online. 

[View Controller Code](https://github.com/zurichat/zc_plugin_todo/blob/develop/app/Http/Controllers/PluginInfoController.php)
[Link To Routing Code Here](https://github.com/zurichat/zc_plugin_todo/blob/develop/routes/web.php)

[Link To PR #223](https://github.com/zurichat/zc_plugin_todo/pull/223)

[Jump To Team-Lead Comment](https://github.com/zurichat/zc_plugin_todo/issues/204#issuecomment-909426017)

**Comment by itz-bethel** [comment]
This issue is cleared for review. - Team Lead

**Comment by EricOgie** [comment]
[View Live Link](https://todo.zuri.chat/plugin-info) 
As you can observe from the Live-Link, The endpoint, https://todo.zuri.chat/plugin-info,  displays static Information of the TODO Plugin in JSON format when you hit the URL link.

[Link To Controller Code Here](https://github.com/zurichat/zc_plugin_todo/blob/master/app/Http/Controllers/PluginInfoController.php)
[Link To Routing Code Here](https://github.com/zurichat/zc_plugin_todo/blob/master/routes/web.php)

[Link To PR #223](https://github.com/zurichat/zc_plugin_todo/pull/223)

**Comment by markessien** [comment]
Rename link to /info, provide the url for the sidebar, provide the url for the full html, provide the url that can be used to ping if it's still alive. The urls should be provided in the return json.

Add two line description and a longer description.


Remove all these: 


team_lead | "Bethel Irumudomon"
-- | --
mvp_features |  
feature-1 | "Create Todo Tasks"
feature-2 | "Assign Tasks To An Individual Or A Team"
feature-3 | "Dispaly Tasks On Cards"
feature-4 | "Manage and Display Task Progress Using Dynamic ProgressBar"
feature-5 | "Set Reminders For Task's Due Date"
feature-6 | "Schedule A Task For Future Commencement"
feature-7 | "Schedule Task Notification And Reminders"
feature-8 | "Manage Workspace Comments On Task"
programming_language |  
0 | "PHP"
1 | "Javascript"
frameworks |  
0 | "Laravel"
1 | "Vue.js"
dependencies |  
0 | "Phpredis"
1 | "Tailwind CSS"

**Comment by EricOgie** [comment]
@markessien  I have made the necessary adjustments as noted in your comment above. Please review

**Comment by markessien** [comment]
Cool
