### ISSUE TITLE
Add An Endpoint That Supplies The List Of TODO Plugin Menu/Sidebar Items 

### ISSUE THREAD

**Issue by EricOgie** [zurichat/zc_plugin_todo#209]
Add An Endpoint That Supplies The List Of TODO Plugin Menu/Sidebar Items in JSON Format

**Comment by itz-bethel** [comment]
An endpoint supplying the list of TODO sidebar items: Schedule, Calendar, Search, Inbox, Task Board.

live link: https://todo.zuri.chat/sidebar

**Comment by EricOgie** [comment]
Cleared for review - PR Team

**Comment by markessien** [comment]
Nice
