### ISSUE TITLE
Create Laravel Email Notification Scaffold

### ISSUE THREAD

**Issue by EricOgie** [zurichat/zc_plugin_todo#22]
Create and add Email Notification Scaffold useable for emailing.

**Comment by victor-ok** [comment]
@itz-bethel I picked this too

**Comment by victor-ok** [comment]
created a scaffolding to notify users of their tasks by mail

endpoint : https://todo.zuri.chat/task-email-notification

**Comment by markessien** [comment]
This ticket references email notification, but there is nothing of that sort here. You are just showing json
