### ISSUE TITLE
Install Vue.js and Tailwind CSS Dependencies 

### ISSUE THREAD

**Issue by EricOgie** [zurichat/zc_plugin_todo#222]
Install Vue.js and Tailwind CSS Dependencies. 
 -Create and configure Tailing configuration file in accordance with Laravel/Tailwind documentation

**Comment by Didier-ds** [comment]
Little configurations will still be made to the tailwind

**Comment by Didier-ds** [comment]
As you can observe from the live link,
It displays a page showing that site is under construction,
I made it to test that Vue and tailwind was working  fine in the laravel project.

[Live link](https://todo.zuri.chat/)

**Comment by markessien** [comment]
Looks good
