### ISSUE TITLE
Add a search method that allows user to search for specific todo

### ISSUE THREAD

**Issue by kayleb01** [zurichat/zc_plugin_todo#299]
Add a search method that searches the Todo to retrieve  the searched todo to the user, either using the title, description or any field

**Comment by kayleb01** [comment]
[View Live Link here](https://todo.zuri.chat/api/search?key=title&q=This+is+a+demo+again)
The search method allows the user to search to a specific Todo either search by Title, description or even date as shown here [https://todo.zuri.chat/api/search?key=title&q=This is a demo again](https://todo.zuri.chat/api/search?key=title&q=This+is+a+demo+again)
The search takes in two fields, the key and q where key is either title, description, data or any part of the Todo data and the q is what is being searched for. 
[View HttpRepository](https://github.com/zurichat/zc_plugin_todo/blob/develop/app/Repositories/HTTP/HTTPRepository.php)
[View TodoController](https://github.com/zurichat/zc_plugin_todo/blob/develop/app/Http/Controllers/TodoController.php)
[View TaskService](https://github.com/zurichat/zc_plugin_todo/blob/develop/app/Services/TaskService.php)
Link to PR [here](https://github.com/zurichat/zc_plugin_todo/pull/300)

**Comment by itz-bethel** [comment]
Cleared for Review - PR Team
