### ISSUE TITLE
Add API For Commenting On TODO Tasks

### ISSUE THREAD

**Issue by EricOgie** [zurichat/zc_plugin_todo#3]
Create a Task comment feature so team members assigned to a task can include comments

**Comment by themobileprof** [comment]
Will like this. @sanyaele

**Comment by themobileprof** [comment]
Resolved with this PR:  #315 
Links to try out on Postman: 
Get: https://todo.zuri.chat/api/comment/6132995da921b9ec34e2033d
POST https://todo.zuri.chat/api/comment/
POST https://todo.zuri.chat/api/comment/6132995da921b9ec34e2033d
