### ISSUE TITLE
Add API For Fetching TODO Task Base On Their Category

### ISSUE THREAD

**Issue by EricOgie** [zurichat/zc_plugin_todo#36]
Create and add an endpoint to fetching TODO task with respect to category

**Comment by vrrayz** [comment]
@TheGrimSavage here to claim this :)

**Comment by vrrayz** [comment]
I've sent a PR for this issue
https://github.com/zurichat/zc_plugin_todo/pull/305

You can now get todo tasks by category_id

Live link to test: https://todo.zuri.chat/api/task-category?category_id=1
