### ISSUE TITLE
Create a section on the plugin that displays newly created task

### ISSUE THREAD

**Issue by Kemmie001** [zurichat/zc_plugin_todo#38]

**Comment by omoh09** [comment]
i pick this issue to work on

**Comment by omoh09** [comment]
LIVE LINK: https://todo.zuri.chat/api/getLatestTask

**Comment by omoh09** [comment]
Describe (in detail) what the task completed in the pull request does
I created an 
How should this be manually tested?
Go to : https://todo.zuri.chat/api/getLatestTask

PR - #296 

slack handle - @omoh
