### ISSUE TITLE
Add API To Fetch TODO For A user

### ISSUE THREAD

**Issue by EricOgie** [zurichat/zc_plugin_todo#486]
When a user loads the plugin, he/she is supposed to have a catalog of TO-DO's comprising of the TODOs that he/she created, and the one he is assigned to.
Create and add an API that fetches a collection of these TODOs.
 
NB: 
  - This is also the same as fetching the rooms the user is actively in

**Comment by ayodejidaniel** [comment]
@EricOgie I will love to work on this
