### ISSUE TITLE
Add API To Sort TODO Tasks BY A Defined Order

### ISSUE THREAD

**Issue by kayleb01** [zurichat/zc_plugin_todo#62]
Write an API to sort all to-do tasks based on user preferences. 

The API should be able to sort Todo tasks base on priority.

**Comment by Itzadetunji** [comment]
Would like to take this 👨🏿‍💻

**Comment by Itzadetunji** [comment]
Heres my live link http://todo.zuri.chat/api/task/sort?sort=category_id
Using this link you can change "category_id" to "workspace_id", "start_date" and 
"created_at"
The tasks assigned will be arranged based on what is passed into the function.
