### ISSUE TITLE
Add Endpoint To Modify Task Due Date

### ISSUE THREAD

**Issue by EricOgie** [zurichat/zc_plugin_todo#67]
Add Endpoint To Modify Task Due Date

**Comment by magnate-tech** [comment]
.Feranmi. I'll like to be assigned

**Comment by magnate-tech** [comment]
I created a function to update a task due date.

endpoint: https://todo.zuri.chat/api/task/modify/156787873
Method: post
payload: {content:"value"}

I created a form to test the function

Live Link: [https://todo.zuri.chat/api/task/modify/156787873](https://todo.zuri.chat/api/task/modify/156787873)

Fill the form and hit the Submit button to update task Due date

**Comment by magnate-tech** [comment]
@Ericogia @EricOgie @kayleb01
